server:
    port: 8080
javax:
    sql:
        DataSource:
            employeeDataSource:
                dataSourceClassName: oracle.jdbc.pool.OracleDataSource
                dataSource:
                    url: jdbc:oracle:thin:@localhost:1521:orcl
                    user: system
                    password: oracle